import { Header } from '@/components/Header';
import './globals.css'
import type { Metadata } from 'next'
import { Saira } from 'next/font/google'

const saira = Saira({ 
  weight: ["300", "400", "500", "600"],
  subsets: ['latin'] 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <Header />

      <body className={saira.className}>{children}</body>
    </html>
  )
}
